spring:
    datasource:
        url: jdbc:mysql://localhost:3306/farel-cigar?useSSL=true
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
    servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    jackson:
      serialization:
        write_dates_as_timestamps: false